### PR TITLE
Bugfixes in labs

### PR DESCRIPTION
**Pull request by chrishtr**
1. Handle <html> elements not preceded by other tokens correctly; in these cases, currently_open will be an empty array
2. Handle URLs not containing a / after the domain
3. s/self/this/ in runtime9.js
4. Output "comment9.js" instead of "comment.js" in server9.js
5. Output the id=errors div in server9.js, which is expected by the script
6. Wrong order of arguments to ElementNode constructor in lab6.py

### CODE REVIEW

**Comment by chrishtr** [comment]
The comparison script for lab4 seems to have gone rogue. It is recording diffs that aren't in my CL...any suggestion or idea?

**Comment by pavpanchekha** [comment]
Yeah the differ could stand a rework now that I've built all this other infra for compiling and outlining. Anyway, fixed it by reminding it that these lines should be indented. I don't understand why it doesn't do that automatically but it helps sometimes.

**Comment by pavpanchekha** [comment]
For the "URLs not containing a slash" I would write that code like this:

```
if (url.find("/") >= 0):
    host, path = url.split("/", 1)
else:
    host, path = url, ""
```

Is there a comparable part of Chapter 1 that we should update?

**Comment by pavpanchekha** [comment]
The "elements not preceded by other ..." that doesn't happen in Ch4, right? The code for labs 6 onward aren't up to date with the changes so far in the book. (Sometimes the changes would be large which is why I don't want to do it before we get to those chapters.)

**Comment by pavpanchekha** [comment]
Other things look good.

**Review by pavpanchekha — APPROVED** [review]

**Comment by chrishtr** [comment]
> For the "URLs not containing a slash" I would write that code like this:
> 
> ```
> if (url.find("/") >= 0):
>     host, path = url.split("/", 1)
> else:
>     host, path = url, ""

Doesn't this have a scoping problem for the variables host and path?

> ```
> 
> Is there a comparable part of Chapter 1 that we should update?

I already fixed it in a previous PR.

**Comment by pavpanchekha** [comment]
There's not a scoping problem in Python—"if" and "for" and so on don't introduce scopes. (I just implemented this in the compiler, since JS semantics are different!)

**Comment by chrishtr** [comment]
> The "elements not preceded by other ..." that doesn't happen in Ch4, right? The code for labs 6 onward aren't up to date with the changes so far in the book. (Sometimes the changes would be large which is why I don't want to do it before we get to those chapters.)

Right. It was only broken for the later labs.

I came across this because I'm working on a lab for my new chapter 13, which needs to riff on chapter 9's code.

**Comment by pavpanchekha** [comment]
Ok sounds good happy to merge this. If you'd like I can bring Ch9 up to date.

**Comment by chrishtr** [comment]
I upda

> There's not a scoping problem in Python—"if" and "for" and so on don't introduce scopes. (I just implemented this in the compiler, since JS semantics are different!)

Got it. I fixed the code then.

**Pull request merged**
